### ISSUE TITLE
build with aot and global options not working

### ISSUE THREAD

**Issue by LaserUnicorns** [JsDaddy/ngx-mask#199]
ngx-mask version - 6.2.8
angular version - 6.1.9

app.module.ts
```
imports: [
  NgxMaskModule.forRoot({
    patterns: {
      D: {
        pattern: new RegExp('\\d'),
      },
    },
  }),
],
```

in template:
```
<input mask="DDD">
```

When I run `ng serve --aot` mask not working correctly, input only accepts character 'D'.

Cusotm global config in MaskService looks like this:

![image](https://user-images.githubusercontent.com/8597726/46299897-10660100-c5ab-11e8-9523-14cfd849fb49.png)

Notice there is no pattern field.

If I build application without aot - everything works fine.

**Comment by NepipenkoIgor** [comment]
@LaserUnicorns  Hi . Thank you for report . We will check

**Comment by Alexandr98** [comment]
@LaserUnicorns Hi. We fixed this in new version 6.3.9

**Comment by Alexandr98** [comment]
@LaserUnicorns Hi. We fixed this in new version 6.3.9

**Comment by LaserUnicorns** [comment]
Still not working in 6.3.11. Seems like angular compiler strips regexes in aot mode.

**Comment by apatel7886** [comment]
Still not working in latest version 6.5.17

**Comment by asp-id** [comment]
Any news? Still not working in 7.3.3

**Comment by Marcidius** [comment]
Same thing, not working in 8.0.5.
