### ISSUE TITLE
'DEL' button does not work when cursor is in front of input

### ISSUE THREAD

**Issue by nellstephanj** [JsDaddy/ngx-mask#620]
Using version "ngx-mask": "^8.1.5".

I am not able to use the 'DEL' button when the cursor is in front of the text input. However, when the cursor is in the middle of the text input it works as expected.

I tested the issue on the [Demo Page](https://jsdaddy.github.io/ngx-mask-page) and I experience the same problem.

**Comment by ColinMorris83** [comment]
Hopefully fixed with this PR: https://github.com/ColinMorris83/ngx-mask/tree/560-patterns-attribute 
Feel free to test out by cloning the repo, then doing following to test it out in the demo app on http://localhost:4200
npm i
npm run build:lib
npm start

**Comment by nellstephanj** [comment]
I tested with the PR above and I am still experiencing the problem.
Hopefully, the GIF will make it a bit more clear about what is happening.
Basically I am able to delete anywhere in the input except when the cursor is at the front of the input.
![Mask](https://user-images.githubusercontent.com/14351578/67949682-cfe31780-fbf0-11e9-81d4-f923085f6b8e.gif)

Thanks for all the help

**Comment by ColinMorris83** [comment]
That's odd, I'm trying the same thing in the Hour field in the demo app and it's deleting ok.

![Screen Recording 2019-10-31 at 13 21 15](https://user-images.githubusercontent.com/25006340/67950652-ecc41e80-fbe1-11e9-9b1b-c702a60fd20e.gif)

**Comment by nellstephanj** [comment]
Not sure what happened but I tried it again and it is working as expected! 😄 Thanks
